### PR TITLE
fix: "Toggle" commponent react export doesn't update state 

### PR DESCRIPTION
**Pull request by prasoonmhwr**
This pull request resolves https://github.com/IBM/carbon-ui-builder/issues/135

### CODE REVIEW

**Comment by zvonimirfras** [comment]
@prasoonmhwr, you're on the right track.

Testing the following fragment in the [deploy preview](https://deploy-preview-165--carbon-components-builder.netlify.app/) with this fragment:

```
{
  "items": [
    {
      "type": "toggle",
      "header": "Toggle",
      "offText": "Off",
      "onText": "On",
      "disabled": false,
      "checked": false,
      "size": "md",
      "id": "856023431236538704152076911133684",
      "codeContext": {
        "name": "toggle-856023431236538704152076911133684"
      }
    },
    {
      "type": "checkbox",
      "label": "Checkbox",
      "id": "19053493579018925117473618283427",
      "codeContext": {
        "name": "checkbox-19053493579018925117473618283427"
      }
    }
  ],
  "id": 1
}
```
You can use import JSON functionality to recreate it.

Checkbox has a nice state of `{"checkbox-19053493579018925117473618283427":true}` <-- boolean

Toggle's state is `{"toggle-856023431236538704152076911133684":{"dispatchConfig":null,"_targetInst":null,"nativeEvent":null,"type":null,"target":null,"eventPhase":null,"bubbles":null,"cancelable":null,"defaultPrevented":null,"isTrusted":null,"_dispatchListeners":null,"_dispatchInstances":null}}` <-- looks like an event object, should get the boolean value out of it

I displayed the state by adding `{JSON.stringify(state)}` below FragmentComponent in CodeSandbox export.

This means that toggle needs to figure out a nice boolean to pass to the state.


Does this make sense?

**Comment by prasoonmhwr** [comment]
> @prasoonmhwr, you're on the right track.
> 
> Testing the following fragment in the [deploy preview](https://deploy-preview-165--carbon-components-builder.netlify.app/) with this fragment:
> 
> ```
> {
>   "items": [
>     {
>       "type": "toggle",
>       "header": "Toggle",
>       "offText": "Off",
>       "onText": "On",
>       "disabled": false,
>       "checked": false,
>       "size": "md",
>       "id": "856023431236538704152076911133684",
>       "codeContext": {
>         "name": "toggle-856023431236538704152076911133684"
>       }
>     },
>     {
>       "type": "checkbox",
>       "label": "Checkbox",
>       "id": "19053493579018925117473618283427",
>       "codeContext": {
>         "name": "checkbox-19053493579018925117473618283427"
>       }
>     }
>   ],
>   "id": 1
> }
> ```
> 
> You can use import JSON functionality to recreate it.
> 
> Checkbox has a nice state of `{"checkbox-19053493579018925117473618283427":true}` <-- boolean
> 
> Toggle's state is `{"toggle-856023431236538704152076911133684":{"dispatchConfig":null,"_targetInst":null,"nativeEvent":null,"type":null,"target":null,"eventPhase":null,"bubbles":null,"cancelable":null,"defaultPrevented":null,"isTrusted":null,"_dispatchListeners":null,"_dispatchInstances":null}}` <-- looks like an event object, should get the boolean value out of it
> 
> I displayed the state by adding `{JSON.stringify(state)}` below FragmentComponent in CodeSandbox export.
> 
> This means that toggle needs to figure out a nice boolean to pass to the state.
> 
> Does this make sense?

Looking into it

**Comment by prasoonmhwr** [comment]
@zvonimirfras I have corrected it please check again.


https://user-images.githubusercontent.com/52622674/196029592-27733ca3-29ae-4723-b757-c50bfab3d88d.mov

**Comment by zvonimirfras** [comment]
It is, thank you!

**Comment by zvonimirfras** [comment]
> > It is, thank you!
> 
> Can I ask a favor , can you star this repo(https://github.com/prasoonmhwr/prasoonmhwr)

What do you get from that? 🤔

**Comment by prasoonmhwr** [comment]
> > > It is, thank you!
> > 
> > Can I ask a favor , can you star this repo(https://github.com/prasoonmhwr/prasoonmhwr)
> 
> What do you get from that? 🤔 

Just trying to increase my visibility 😅

**Pull request merged**
